services:
  db:
    container_name: app_store_db
    image: postgres:latest
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"
    env_file:
      - ./secrets/db/.env

  backend:
    container_name: app_store_api
    depends_on:
      - db
    stdin_open: true
    tty: true
    ports:
      - "8290:8200"
    build:
      context: ./src/backend
      dockerfile: Dockerfile.dev
      args:
        HTTP_PORT: 8200
    develop:
      watch:
        - action: sync+restart
          path: ./src/backend
          target: /app/src/backend/
    env_file:
      - ./secrets/backend/.env

volumes:
  api_volumes: