INSERT INTO categories (name, description) 
VALUES 
    ('Electronics', 'Devices and gadgets like phones, laptops, and televisions.'),
    ('Home Appliances', 'Machines and devices used in household tasks such as washing, cooking, and cleaning.'),
    ('Furniture', 'Items used to furnish spaces, such as chairs, tables, and sofas.'),
    ('Clothing', 'Garments like shirts, pants, dresses, and outerwear.'),
    ('Beauty', 'Cosmetics, skincare, and personal care products.'),
    ('Toys', 'Products designed for play, especially for children.'),
    ('Books', 'Printed works and publications, both fiction and non-fiction.'),
    ('Groceries', 'Everyday food items and household consumables.'),
    ('Sporting Goods', 'Equipment and gear for various sports and outdoor activities.'),
    ('Automotive', 'Car accessories, parts, and tools.'),
    ('Jewelry', 'Accessories made of precious metals and stones.'),
    ('Health', 'Products related to fitness, wellness, and medical care.'),
    ('Office Supplies', 'Products needed for office work, like pens, paper, and printer ink.'),
    ('Garden', 'Items used for outdoor gardening and landscaping.'),
    ('Pet Supplies', 'Food, toys, and other products for pets.'),
    ('Music', 'Instruments, accessories, and music-related products.'),
    ('Art Supplies', 'Materials used for creating art, like paint, brushes, and canvas.'),
    ('Baby', 'Products specifically for babies, including clothes, toys, and care items.'),
    ('Travel', 'Luggage, accessories, and items related to travel and adventure.'),
    ('Beauty & Personal Care', 'Products and services related to skincare, cosmetics, personal hygiene, and grooming.'),
    ('Sports & Outdoors', 'Products and services related to sports equipment, outdoor activities, fitness, and recreation.'),
    ('Toys & Games', 'Products related to toys, games, puzzles, educational play, and entertainment for children and families.'),
    ('Health & Wellness', 'A category dedicated to wellness, healthy living, fitness, mental health, and overall well-being.'),
    ('Food & Beverages', 'Products related to eating and drinking, including packaged foods and drinks.');
